import type { Theme } from './theme';

/**
 * The built-in themes.
 *
 * A theme is a design dressed in colours, and the name says what it looks like, never what it is for: the same
 * gold block frame suits a Minecraft series and a chess final, the same navy panel a table tennis final and a
 * quiz. Names are "<what it is> · <how it looks>".
 *
 * Every one is drawn to be read at a glance on moving picture: strong contrast between the text and the panel it
 * sits on, the numbers in their own boxes or on their own colour, and no flat pastel or olive tones. Several are
 * drawn after real television graphics (the first of each design); the rest are our own variations on the same
 * structure. The first theme in the list is the default.
 */

type Spec = Pick<Theme, 'name' | 'design' | 'font' | 'primary' | 'secondary' | 'tertiary' | 'text' | 'accent' | 'sides'> & Partial<Theme>;

const theme = (spec: Spec): Theme => ({
  background: { angle: 180, stops: [spec.primary, spec.tertiary] },
  radius: 0,
  shadow: 'soft',
  animation: 'slide',
  ...spec,
});

export const DEFAULT_THEMES: Theme[] = [
  /* ---------------------------------------------------------------- panel: a lower panel with a name row per side */
  theme({
    // After the lower panel of a table tennis world tour broadcast: navy, a red box for sets, a dark box for points.
    name: 'Panel · Marin',
    design: 'broadcast',
    font: 'condensed',
    primary: '#1d2a6a',
    secondary: '#c8102e',
    tertiary: '#141d4c',
    text: '#ffffff',
    accent: '#ffffff',
    sides: ['#c8102e', '#1d2a6a'],
  }),
  theme({
    name: 'Panel · Skog',
    design: 'broadcast',
    font: 'condensed',
    primary: '#0f4a37',
    secondary: '#c9930d',
    tertiary: '#082e22',
    text: '#ffffff',
    accent: '#ffd76a',
    sides: ['#c9930d', '#0f4a37'],
  }),
  theme({
    name: 'Panel · Kol',
    design: 'broadcast',
    font: 'condensed',
    primary: '#20242d',
    secondary: '#ff5a1f',
    tertiary: '#0f1116',
    text: '#ffffff',
    accent: '#ffb27a',
    sides: ['#ff5a1f', '#5b6577'],
    shadow: 'deep',
    animation: 'pop',
  }),
  theme({
    name: 'Panel · Petrol',
    design: 'broadcast',
    font: 'condensed',
    primary: '#0c4a5a',
    secondary: '#e8563a',
    tertiary: '#062f3a',
    text: '#ffffff',
    accent: '#7fe3d6',
    sides: ['#e8563a', '#0c4a5a'],
    animation: 'flip',
  }),

  /* ---------------------------------------------------------------- staplar: full-width bars over a swoosh */
  theme({
    // After a handball broadcast's result bars: bright blue, a heading on top, scores either side of two logo blocks.
    name: 'Staplar · Himmel',
    design: 'bars',
    font: 'sans',
    primary: '#2f8fd6',
    secondary: '#ffffff',
    tertiary: '#1d6db0',
    text: '#ffffff',
    accent: '#7cc4f5',
    sides: ['#e2001a', '#0a0a0a'],
    background: { angle: 100, stops: ['#3b9ae0', '#57aeea', '#2a86cd', '#4aa3e4'] },
    shadow: 'none',
    animation: 'pop',
  }),
  theme({
    name: 'Staplar · Solnedgång',
    design: 'bars',
    font: 'sans',
    primary: '#ff5a3d',
    secondary: '#ffffff',
    tertiary: '#7a2cff',
    text: '#ffffff',
    accent: '#ffd2a8',
    sides: ['#1b1230', '#3a1c6e'],
    background: { angle: 100, stops: ['#ff6a3d', '#ff3d7f', '#8a35ff', '#ff5a6e'] },
    shadow: 'none',
    animation: 'pop',
  }),
  theme({
    name: 'Staplar · Natt',
    design: 'bars',
    font: 'sans',
    primary: '#0a1330',
    secondary: '#ffffff',
    tertiary: '#14285c',
    text: '#ffffff',
    accent: '#5fd4ff',
    sides: ['#19b8ff', '#ff3d6e'],
    background: { angle: 100, stops: ['#081029', '#15295e', '#0a1633', '#1c3a80'] },
    shadow: 'none',
    animation: 'slide',
  }),
  theme({
    name: 'Staplar · Grön',
    design: 'bars',
    font: 'sans',
    primary: '#0b6b4a',
    secondary: '#ffffff',
    tertiary: '#08523a',
    text: '#ffffff',
    accent: '#8ff0c0',
    sides: ['#f2c200', '#101010'],
    background: { angle: 100, stops: ['#0b6b4a', '#14956a', '#0a5c40', '#19a878'] },
    shadow: 'none',
    animation: 'flip',
  }),

  /* ---------------------------------------------------------------- tvåton: a light row, a dark row, a block for the clock */
  theme({
    // After a college scorebug: white row with red type, navy row, a navy block for the clock and the period.
    name: 'Tvåton · Marin',
    design: 'college',
    font: 'condensed',
    primary: '#1f3350',
    secondary: '#c8202e',
    tertiary: '#ffffff',
    text: '#ffffff',
    accent: '#ffffff',
    sides: ['#c8202e', '#1f3350'],
    animation: 'none',
  }),
  theme({
    name: 'Tvåton · Vinröd',
    design: 'college',
    font: 'condensed',
    primary: '#5a1026',
    secondary: '#b3122f',
    tertiary: '#fff8f0',
    text: '#ffffff',
    accent: '#ffd9b8',
    sides: ['#b3122f', '#5a1026'],
    animation: 'none',
  }),
  theme({
    name: 'Tvåton · Kol',
    design: 'college',
    font: 'condensed',
    primary: '#22252c',
    secondary: '#2b2f38',
    tertiary: '#eceef2',
    text: '#ffffff',
    accent: '#ff9d2e',
    sides: ['#ff9d2e', '#22252c'],
    animation: 'pop',
  }),
  theme({
    name: 'Tvåton · Skog',
    design: 'college',
    font: 'condensed',
    primary: '#0f3d2e',
    secondary: '#0f6b4b',
    tertiary: '#ffffff',
    text: '#ffffff',
    accent: '#ffd76a',
    sides: ['#0f6b4b', '#0f3d2e'],
    animation: 'none',
  }),

  /* ---------------------------------------------------------------- block: blocks in a pixel face, a window for the picture */
  theme({
    // After a Minecraft overlay: gold blocks, dark boxes for the numbers, orange for the small print.
    name: 'Block · Guld',
    design: 'pixel',
    font: 'pixel',
    primary: '#e7cf45',
    secondary: '#3a2a08',
    tertiary: '#b8952a',
    text: '#2a1a04',
    accent: '#f08a1a',
    sides: ['#3a2a08', '#3a2a08'],
    background: { angle: 180, stops: ['#f3dd62', '#d9bb34'] },
    shadow: 'none',
    animation: 'none',
  }),
  theme({
    name: 'Block · Smaragd',
    design: 'pixel',
    font: 'pixel',
    primary: '#2fc266',
    secondary: '#0d3b1f',
    tertiary: '#1a8f45',
    text: '#062a14',
    accent: '#fff2a6',
    sides: ['#0d3b1f', '#0d3b1f'],
    shadow: 'none',
    animation: 'none',
  }),
  theme({
    name: 'Block · Diamant',
    design: 'pixel',
    font: 'pixel',
    primary: '#58e6dd',
    secondary: '#0b2f3a',
    tertiary: '#1fa39d',
    text: '#062a30',
    accent: '#ff8a1f',
    sides: ['#0b2f3a', '#0b2f3a'],
    shadow: 'none',
    animation: 'none',
  }),
  theme({
    name: 'Block · Rödsten',
    design: 'pixel',
    font: 'pixel',
    primary: '#d8392b',
    secondary: '#3a0d08',
    tertiary: '#8f1d14',
    text: '#ffffff',
    accent: '#ffd25a',
    sides: ['#3a0d08', '#3a0d08'],
    shadow: 'none',
    animation: 'none',
  }),

  /* ---------------------------------------------------------------- bred: a wide bar with slanted colour ends (our own) */
  theme({
    name: 'Bred · Neon',
    design: 'league',
    font: 'condensed',
    primary: '#150a33',
    secondary: '#0a0518',
    tertiary: '#2b1466',
    text: '#ffffff',
    accent: '#ff3fd0',
    sides: ['#ff2f7d', '#1fd1ff'],
    shadow: 'deep',
    animation: 'pop',
  }),
  theme({
    name: 'Bred · Guld',
    design: 'league',
    font: 'condensed',
    primary: '#17171b',
    secondary: '#0c0c0f',
    tertiary: '#2c2c33',
    text: '#ffffff',
    accent: '#f5c542',
    sides: ['#b8860b', '#6f4e0a'],
    shadow: 'deep',
    animation: 'flip',
  }),
  theme({
    name: 'Bred · Is',
    design: 'league',
    font: 'sans',
    primary: '#0b2a4a',
    secondary: '#071b31',
    tertiary: '#14487d',
    text: '#ffffff',
    accent: '#7fd8ff',
    sides: ['#1e88e5', '#ff7a45'],
    shadow: 'deep',
    animation: 'slide',
  }),

  /* ---------------------------------------------------------------- lagfärg: each row in its side's colour */
  theme({
    name: 'Lagfärg · Klassisk',
    design: 'stack',
    font: 'condensed',
    primary: '#10151f',
    secondary: '#ffffff',
    tertiary: '#0a0d14',
    text: '#ffffff',
    accent: '#ffd54a',
    sides: ['#c8102e', '#0f4c9c'],
    animation: 'pop',
  }),
  theme({
    name: 'Lagfärg · Natt',
    design: 'stack',
    font: 'sans',
    primary: '#120b26',
    secondary: '#ffffff',
    tertiary: '#0a0618',
    text: '#ffffff',
    accent: '#5ff5e0',
    sides: ['#7b2ff7', '#00a99d'],
    shadow: 'deep',
    animation: 'slide',
  }),
  theme({
    name: 'Lagfärg · Sol',
    design: 'stack',
    font: 'condensed',
    primary: '#241a0a',
    secondary: '#ffffff',
    tertiary: '#140e05',
    text: '#ffffff',
    accent: '#ffe08a',
    sides: ['#f2b705', '#0f7a4a'],
    animation: 'flip',
  }),

  /* ---------------------------------------------------------------- kapsel: a rounded capsule with round score badges (our own) */
  theme({
    name: 'Kapsel · Isvit',
    design: 'pill',
    font: 'sans',
    primary: '#0b1730',
    secondary: '#ffffff',
    tertiary: '#13264d',
    text: '#ffffff',
    accent: '#8fd0ff',
    sides: ['#1e6fd9', '#e8452c'],
    shadow: 'deep',
    animation: 'pop',
  }),
  theme({
    name: 'Kapsel · Neon',
    design: 'pill',
    font: 'condensed',
    primary: '#0d0620',
    secondary: '#1f0d47',
    tertiary: '#1a0b3d',
    text: '#ffffff',
    accent: '#19e6ff',
    sides: ['#ff2fd0', '#18a8ff'],
    shadow: 'deep',
    animation: 'flip',
  }),

  /* ---------------------------------------------------------------- namnbalk: a name bar with a stripe at the end */
  theme({
    // After a plain broadcast name bar: chunky navy with a white stripe at the end.
    name: 'Namnbalk · Marin',
    design: 'block',
    font: 'sans',
    primary: '#0d1b4e',
    secondary: '#ffffff',
    tertiary: '#0d1b4e',
    text: '#ffffff',
    accent: '#ffffff',
    sides: ['#ffffff', '#ffffff'],
  }),
  theme({
    name: 'Namnbalk · Vit',
    design: 'block',
    font: 'sans',
    primary: '#ffffff',
    secondary: '#e63946',
    tertiary: '#ffffff',
    text: '#0d1b4e',
    accent: '#e63946',
    sides: ['#e63946', '#e63946'],
    shadow: 'deep',
  }),
  theme({
    name: 'Namnbalk · Karmosin',
    design: 'block',
    font: 'sans',
    primary: '#a10f2b',
    secondary: '#ffffff',
    tertiary: '#a10f2b',
    text: '#ffffff',
    accent: '#ffd9e0',
    sides: ['#ffffff', '#ffffff'],
    animation: 'pop',
  }),
  theme({
    name: 'Namnbalk · Svart',
    design: 'block',
    font: 'display',
    primary: '#0b0b0d',
    secondary: '#ffcc00',
    tertiary: '#0b0b0d',
    text: '#ffffff',
    accent: '#ffcc00',
    sides: ['#ffcc00', '#ffcc00'],
    shadow: 'deep',
  }),

  /* ---------------------------------------------------------------- band: two slanted strips (our own) */
  theme({
    name: 'Band · Magenta',
    design: 'ribbon',
    font: 'sans',
    primary: '#150a33',
    secondary: '#ff2f7d',
    tertiary: '#2b1466',
    text: '#ffffff',
    accent: '#ffd1e6',
    sides: ['#ff2f7d', '#1fd1ff'],
    shadow: 'deep',
  }),
  theme({
    name: 'Band · Turkos',
    design: 'ribbon',
    font: 'sans',
    primary: '#06202b',
    secondary: '#12d0bb',
    tertiary: '#0c3a4a',
    text: '#ffffff',
    accent: '#a8fff2',
    sides: ['#12d0bb', '#0c3a4a'],
    shadow: 'deep',
    animation: 'pop',
  }),
  theme({
    name: 'Band · Guld',
    design: 'ribbon',
    font: 'display',
    primary: '#111114',
    secondary: '#e8b021',
    tertiary: '#26262c',
    text: '#ffffff',
    accent: '#ffe08a',
    sides: ['#e8b021', '#26262c'],
    shadow: 'deep',
    animation: 'flip',
  }),

  /* ---------------------------------------------------------------- flik: a name box with a tab above it (our own) */
  theme({
    name: 'Flik · Vit',
    design: 'tag',
    font: 'sans',
    primary: '#ffffff',
    secondary: '#e63946',
    tertiary: '#ffffff',
    text: '#0d1b4e',
    accent: '#e63946',
    sides: ['#e63946', '#e63946'],
    shadow: 'deep',
    radius: 6,
  }),
  theme({
    name: 'Flik · Turkos',
    design: 'tag',
    font: 'condensed',
    primary: '#072a34',
    secondary: '#17c3b2',
    tertiary: '#072a34',
    text: '#ffffff',
    accent: '#17c3b2',
    sides: ['#17c3b2', '#17c3b2'],
    shadow: 'deep',
    animation: 'pop',
  }),

  /* ---------------------------------------------------------------- linje: type on the picture with a line under it (our own) */
  theme({
    name: 'Linje · Vit',
    design: 'line',
    font: 'sans',
    primary: '#000000',
    secondary: '#ffffff',
    tertiary: '#000000',
    text: '#ffffff',
    accent: '#ffd166',
    sides: ['#ffd166', '#ffd166'],
    animation: 'slide',
  }),
  theme({
    name: 'Linje · Neon',
    design: 'line',
    font: 'condensed',
    primary: '#000000',
    secondary: '#19e6ff',
    tertiary: '#000000',
    text: '#ffffff',
    accent: '#19e6ff',
    sides: ['#19e6ff', '#ff2fd0'],
    animation: 'pop',
  }),
];
